### ISSUE TITLE
Manage Class Sections (Professor)

### ISSUE THREAD

**Issue by CalebWhittington** [rbose365/ProjectrFall2017#10]
## Story/Task Details
[ ] Instructors should be able to manage class sections
[ ] A 'Manage Class Sections' page presents relevant information concisely
[ ] Instructors Should be able to make multiple Sections

## Acceptance Criteria
* Given: A user is an instructor
* When: They click on a link labeled 'Manage Class Sections'
* Then: They can see all of their class sections and have options to edit, remove, etc...

## Testing Done
[ ] Only instructors and admins can manage class sections
[ ] Page represents accurate and up to date information

**Comment by CalebWhittington** [comment]
7

**Comment by ydo30** [comment]
13

**Comment by dkim630** [comment]
13
