### ISSUE TITLE
Accept Bids (Professor)

### ISSUE THREAD

**Issue by ydo30** [rbose365/ProjectrFall2017#11]
## Story/Task Details
[ ] Professors accept a bid for a project.
[ ] Professors should be able to only accept one bid for a project.
[ ] One team cannot be assigned to multiple projects.

## Acceptance Criteria
* Given: a professor is on the corresponding "Review Bids" page and has not assigned any group to the project
* When: a professor selects "Accept" and clicks the "Submit" button
* Then: The team who owns the bid is assigned with the project, the status of the bid is changed to accepted, and the status of all other bids for the project is changed to rejected

## Testing Done
[ ] Only professors who created the project can view the bids submitted by students.
[ ] Professors can accept a bid for a project.

**Comment by CalebWhittington** [comment]
5

**Comment by rbose365** [comment]
8

**Comment by ydo30** [comment]
5

**Comment by dkim630** [comment]
8
