### ISSUE TITLE
Sort Bids (Student)

### ISSUE THREAD

**Issue by ydo30** [rbose365/ProjectrFall2017#12]
## Story/Task Details
[ ] Students should be able to search the list of projects by the keywords of the project.
[ ] Students should be able to sort the list of projects by the number of bids already submitted to the project.

## Acceptance Criteria
* Given: A student is on the "View Bids" page
* When: The student presses the "Sort Button" after selecting specific characteristic
* Then: The student can see all bids sorted by the specific characteristic.

**Comment by CalebWhittington** [comment]
5

**Comment by rbose365** [comment]
13

**Comment by ydo30** [comment]
13

**Comment by dkim630** [comment]
13
