### ISSUE TITLE
Hiding Notifications (All Users)

### ISSUE THREAD

**Issue by CalebWhittington** [rbose365/ProjectrFall2017#13]
## Story/Task Details
[ ] Users should have the ability to hide notifications

## Acceptance Criteria
* Given: A user has received a notification
* When: They click on a certain link in the upper right of the notification
* Then: The notification is no longer visible on the dashboard

## Testing Done
[ ] Notification is hidden after the link in the upper right of the notification is clicked
[ ] Notification remains hidden (after logging out and logging back in as well)
[ ] All users can hide notifications

**Comment by CalebWhittington** [comment]
13

**Comment by rbose365** [comment]
13

**Comment by ydo30** [comment]
13

**Comment by dkim630** [comment]
13
