### ISSUE TITLE
 Changing Section (Student)

### ISSUE THREAD

**Issue by bmock96** [rbose365/ProjectrFall2017#15]
## Story/Task Details
[ ] Student should be able to change class sections

## Acceptance Criteria
* Given: A student has registered
* When: A new section is created
* Then: They are able to join an available section

## Testing Done
[] If a there are available sections, a user is able to switch sections.

**Comment by CalebWhittington** [comment]
8

**Comment by rbose365** [comment]
I don't think they should be able to register without a section

**Comment by rbose365** [comment]
8

**Comment by ydo30** [comment]
13

**Comment by dkim630** [comment]
8
