### ISSUE TITLE
Reply to Messages (Student, Instructor)

### ISSUE THREAD

**Issue by bmock96** [rbose365/ProjectrFall2017#16]
## Story/Task Details
[ ] Students and Instructors should be able to reply to messages in their inbox

## Acceptance Criteria
* Given: A user has received as messages
* When: A user clicks on the reply button
* Then: The user is able to reply with a message to the sender

## Testing Done
[] If a user is sent a message, they are able to view message
[] When users click reply button, they are able to send a message to the sender

**Comment by CalebWhittington** [comment]
13

**Comment by rbose365** [comment]
13

**Comment by ydo30** [comment]
13
