### ISSUE TITLE
Add Tags to Profile (Student)

### ISSUE THREAD

**Issue by dkim630** [rbose365/ProjectrFall2017#23]
## Story/Task Details
[ ] Students add tags to their profile.
[ ] Students should not be able to add a tag that already exists.

## Acceptance Criteria
* Given: Student is on the "Add Tags To Profile" page
* When: Student adds a new tag and clicks the "Submit" button
* Then: Student adds a tag to his/her profile

**Comment by CalebWhittington** [comment]
13

**Comment by rbose365** [comment]
13

**Comment by ydo30** [comment]
13

**Comment by dkim630** [comment]
21
