### ISSUE TITLE
Submit Request to Fix Project Description

### ISSUE THREAD

**Issue by dkim630** [rbose365/ProjectrFall2017#24]
## Story/Task Details
[ ] Clients submit a request to fix errors in project descriptions.

## Acceptance Criteria
* Given: Client is on "Request Error" page and is client for the specific project
* When: Client explains what the error is, selects project he/she is submitting request for, and clicks the "Submit" button
* Then: Client sends a request for an administrator to approve.

**Comment by rbose365** [comment]
I think max had a similar story please look at it.

**Comment by rbose365** [comment]
8

**Comment by ydo30** [comment]
3

**Comment by dkim630** [comment]
8
