### ISSUE TITLE
Create an admin account

### ISSUE THREAD

**Issue by rbose365** [rbose365/ProjectrFall2017#5]
## Story/Task Details
[ ] Admin account should automatically be created
[ ] Password should be able to be changed
[ ] Admin can log in through website
[ ] Password should be randomly generated and sent to admin
[ ] There can only be one

## Acceptance Criteria
* Given: A user is an admin
* When: They try to log in
* Then: They log in as an admin

## Testing Done
[ ] Only one admin account
[ ] On server creation an admin should be created
[ ] Password is successfully changed
[ ] Admin can log in with only correct credentials
[ ] Password is sufficiently random
[ ] Admin can lookup/is sent password

**Comment by CalebWhittington** [comment]
8

**Comment by rbose365** [comment]
21

**Comment by ydo30** [comment]
21

**Comment by dkim630** [comment]
21
