### ISSUE TITLE
Teams Can Bid on a Project Only Once

### ISSUE THREAD

**Issue by rbose365** [rbose365/ProjectrFall2017#6]
## Story/Task Details
[ ] Students should be able to submit only one bid on each project

## Acceptance Criteria
* Given: A user is a student
* When: They bid on a project
* Then: They cannot submit any more bids on that project

## Testing Done
[ ] Students cannot submit more than one bid per project
[ ] Students can submit bids on multiple projects

**Comment by CalebWhittington** [comment]
3

**Comment by rbose365** [comment]
3

**Comment by ydo30** [comment]
2

**Comment by dkim630** [comment]
5

**Comment by CalebWhittington** [comment]
I recycled this duplicate user story to clean up the closed pipeline a bit.

3
