### ISSUE TITLE
Read keys from database

### ISSUE THREAD

**Issue by rbose365** [rbose365/ProjectrFall2017#7]
## Story/Task Details
[ ] Keys should be looked up from database when an instructor registers

## Acceptance Criteria
* Given: An instructor has a valid key
* When: An instructor registers with the key
* Then: The instructor registers successfully

## Testing Done
[ ] An incorrect key is not accepted
[ ] A correct key is accepted
[ ] If there is no key, an error message shows up

**Comment by CalebWhittington** [comment]
5

**Comment by rbose365** [comment]
3

**Comment by ydo30** [comment]
2

**Comment by dkim630** [comment]
3
